#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Game.Droid.Resource", IsApplication=true)]

namespace Game.Droid
{
	
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7F010000
			public const int colorAccent = 2130771968;
			
			// aapt resource value: 0x7F010001
			public const int colorPrimary = 2130771969;
			
			// aapt resource value: 0x7F010002
			public const int colorPrimaryDark = 2130771970;
			
			// aapt resource value: 0x7F010003
			public const int launcher_background = 2130771971;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F020000
			public const int about_game = 2130837504;
			
			// aapt resource value: 0x7F020001
			public const int action_ability = 2130837505;
			
			// aapt resource value: 0x7F020002
			public const int action_attack = 2130837506;
			
			// aapt resource value: 0x7F020003
			public const int action_default = 2130837507;
			
			// aapt resource value: 0x7F020004
			public const int action_move = 2130837508;
			
			// aapt resource value: 0x7F020005
			public const int alpaca1 = 2130837509;
			
			// aapt resource value: 0x7F020006
			public const int alpaca2 = 2130837510;
			
			// aapt resource value: 0x7F020007
			public const int alpaca3 = 2130837511;
			
			// aapt resource value: 0x7F020008
			public const int alpacaclanlogo = 2130837512;
			
			// aapt resource value: 0x7F020009
			public const int attackpopup = 2130837513;
			
			// aapt resource value: 0x7F02000A
			public const int autobattle = 2130837514;
			
			// aapt resource value: 0x7F02000B
			public const int basic_boots = 2130837515;
			
			// aapt resource value: 0x7F02000C
			public const int basic_earring = 2130837516;
			
			// aapt resource value: 0x7F02000D
			public const int basic_earring2 = 2130837517;
			
			// aapt resource value: 0x7F02000E
			public const int basic_earring3 = 2130837518;
			
			// aapt resource value: 0x7F02000F
			public const int basic_hat = 2130837519;
			
			// aapt resource value: 0x7F020010
			public const int basic_hat2 = 2130837520;
			
			// aapt resource value: 0x7F020011
			public const int basic_necklace = 2130837521;
			
			// aapt resource value: 0x7F020012
			public const int basic_necklace2 = 2130837522;
			
			// aapt resource value: 0x7F020013
			public const int basic_scarf = 2130837523;
			
			// aapt resource value: 0x7F020014
			public const int basic_shield = 2130837524;
			
			// aapt resource value: 0x7F020015
			public const int basic_shield2 = 2130837525;
			
			// aapt resource value: 0x7F020016
			public const int basic_shield3 = 2130837526;
			
			// aapt resource value: 0x7F020017
			public const int basic_slippers = 2130837527;
			
			// aapt resource value: 0x7F020018
			public const int basic_socks = 2130837528;
			
			// aapt resource value: 0x7F020019
			public const int basic_sombrero = 2130837529;
			
			// aapt resource value: 0x7F02001A
			public const int basic_stick = 2130837530;
			
			// aapt resource value: 0x7F02001B
			public const int basic_sword = 2130837531;
			
			// aapt resource value: 0x7F02001C
			public const int basic_torch = 2130837532;
			
			// aapt resource value: 0x7F02001D
			public const int battleBackground = 2130837533;
			
			// aapt resource value: 0x7F02001E
			public const int battleboard = 2130837534;
			
			// aapt resource value: 0x7F02001F
			public const int button_continegame = 2130837535;
			
			// aapt resource value: 0x7F020020
			public const int button_delete = 2130837536;
			
			// aapt resource value: 0x7F020021
			public const int button_start = 2130837537;
			
			// aapt resource value: 0x7F020022
			public const int button_startgame = 2130837538;
			
			// aapt resource value: 0x7F020023
			public const int caverns = 2130837539;
			
			// aapt resource value: 0x7F020024
			public const int characters = 2130837540;
			
			// aapt resource value: 0x7F020025
			public const int d10 = 2130837541;
			
			// aapt resource value: 0x7F020026
			public const int d20_2 = 2130837542;
			
			// aapt resource value: 0x7F020027
			public const int dice = 2130837543;
			
			// aapt resource value: 0x7F020028
			public const int exit = 2130837544;
			
			// aapt resource value: 0x7F020029
			public const int homebackground = 2130837545;
			
			// aapt resource value: 0x7F02002A
			public const int icon_add = 2130837546;
			
			// aapt resource value: 0x7F02002B
			public const int icon_back = 2130837547;
			
			// aapt resource value: 0x7F02002C
			public const int icon_cancel = 2130837548;
			
			// aapt resource value: 0x7F02002D
			public const int icon_delete = 2130837549;
			
			// aapt resource value: 0x7F02002E
			public const int icon_dice = 2130837550;
			
			// aapt resource value: 0x7F02002F
			public const int icon_edit = 2130837551;
			
			// aapt resource value: 0x7F020030
			public const int icon_home = 2130837552;
			
			// aapt resource value: 0x7F020031
			public const int icon_new = 2130837553;
			
			// aapt resource value: 0x7F020032
			public const int icon_save = 2130837554;
			
			// aapt resource value: 0x7F020033
			public const int items = 2130837555;
			
			// aapt resource value: 0x7F020034
			public const int knight = 2130837556;
			
			// aapt resource value: 0x7F020035
			public const int leftarrow = 2130837557;
			
			// aapt resource value: 0x7F020036
			public const int llama1 = 2130837558;
			
			// aapt resource value: 0x7F020037
			public const int llama2 = 2130837559;
			
			// aapt resource value: 0x7F020038
			public const int llama3 = 2130837560;
			
			// aapt resource value: 0x7F020039
			public const int llamaclanlogo = 2130837561;
			
			// aapt resource value: 0x7F02003A
			public const int logo = 2130837562;
			
			// aapt resource value: 0x7F02003B
			public const int monster = 2130837563;
			
			// aapt resource value: 0x7F02003C
			public const int monster1 = 2130837564;
			
			// aapt resource value: 0x7F02003D
			public const int monster2 = 2130837565;
			
			// aapt resource value: 0x7F02003E
			public const int monster3 = 2130837566;
			
			// aapt resource value: 0x7F02003F
			public const int monster4 = 2130837567;
			
			// aapt resource value: 0x7F020040
			public const int monster5 = 2130837568;
			
			// aapt resource value: 0x7F020041
			public const int monster6 = 2130837569;
			
			// aapt resource value: 0x7F020042
			public const int monsters = 2130837570;
			
			// aapt resource value: 0x7F020043
			public const int movepopup = 2130837571;
			
			// aapt resource value: 0x7F020044
			public const int obstacle1 = 2130837572;
			
			// aapt resource value: 0x7F020045
			public const int obstacle2 = 2130837573;
			
			// aapt resource value: 0x7F020046
			public const int obstacle3 = 2130837574;
			
			// aapt resource value: 0x7F020047
			public const int rightarrow = 2130837575;
			
			// aapt resource value: 0x7F020048
			public const int score = 2130837576;
			
			// aapt resource value: 0x7F020049
			public const int slider_thumbnail = 2130837577;
			
			// aapt resource value: 0x7F02004A
			public const int startgame = 2130837578;
			
			// aapt resource value: 0x7F02004B
			public const int unique_andeancuff = 2130837579;
			
			// aapt resource value: 0x7F02004C
			public const int unique_andeanhat = 2130837580;
			
			// aapt resource value: 0x7F02004D
			public const int unique_andeanscarf = 2130837581;
			
			// aapt resource value: 0x7F02004E
			public const int unique_bronzemace = 2130837582;
			
			// aapt resource value: 0x7F02004F
			public const int unique_bronzespear = 2130837583;
			
			// aapt resource value: 0x7F020050
			public const int unique_curvedbow = 2130837584;
			
			// aapt resource value: 0x7F020051
			public const int unique_fedora = 2130837585;
			
			// aapt resource value: 0x7F020052
			public const int unique_incanscarf = 2130837586;
			
			// aapt resource value: 0x7F020053
			public const int unique_puregoldenanklet = 2130837587;
			
			// aapt resource value: 0x7F020054
			public const int unique_puregoldring = 2130837588;
			
			// aapt resource value: 0x7F020055
			public const int unique_puresilveranklet = 2130837589;
			
			// aapt resource value: 0x7F020056
			public const int unique_tumiring = 2130837590;
			
			// aapt resource value: 0x7F020057
			public const int vicuna1 = 2130837591;
			
			// aapt resource value: 0x7F020058
			public const int vicuna2 = 2130837592;
			
			// aapt resource value: 0x7F020059
			public const int vicuna3 = 2130837593;
			
			// aapt resource value: 0x7F02005A
			public const int vicunaclanlogo = 2130837594;
			
			// aapt resource value: 0x7F02005B
			public const int village = 2130837595;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7F030000
			public const int icon = 2130903040;
			
			// aapt resource value: 0x7F030001
			public const int icon_round = 2130903041;
			
			// aapt resource value: 0x7F030002
			public const int launcher_foreground = 2130903042;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7F040000
			public const int MainTheme = 2130968576;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
